name: fasotransport_mobile
description: FasoTransport mobile app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  mobile_scanner: ^5.1.1
  google_fonts: ^6.2.1
  shared_preferences: ^2.2.3
  pdf: ^3.11.1
  path_provider: ^2.1.5
  share_plus: ^10.1.2
  image_picker: ^1.1.2
  image: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
